# Generated by Django 3.2.3 on 2021-09-20 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=245)),
                ('email', models.EmailField(max_length=245, unique=True)),
                ('bio', models.CharField(blank=True, max_length=101, null=True)),
                ('pro_img', models.ImageField(default='auth/pro_img/abstract-user-flat-4.svg', upload_to='auth/pro_img')),
                ('token', models.CharField(blank=True, max_length=245, null=True)),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
